# Template configuration for Convertigo project CI build on GitHub Actions
# Please consult the GitHub documentation for details about settings
# https://docs.github.com/en/actions
#
# This sample assumes you have declared the following Encrypted Secrets
# https://docs.github.com/en/actions/reference/encrypted-secrets
#
# C8O_SERVEUR_TEST_CONVERTIGO: Convertigo server endpoint
#   example: https://<myhost>/convertigo
# C8O_USER_TEST_CONVERTIGO: Convertigo admin user or PROJECTS_CONFIG user
# C8O_PASSWORD_TEST_CONVERTIGO: password for C8O_USER_TEST_CONVERTIGO
#
# Discover all tasks and -Pconvertigo options in your project build.gradle file.

name: Convertigo CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
            path: |
               ~/.gradle/caches
               ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-caches-v1-${{ hashFiles('**/*.gradle', '**/gradle/wrapper/gradle-wrapper.properties') }}
            restore-keys: ${{ runner.os }}-gradle-caches-v1-

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
            path: |
              ${{ github.workspace }}/_private/ionic/node_modules
              ${{ github.workspace }}/_private/ionic/.angular
              /home/runner/convertigo/nodes
            key: ${{ runner.os }}-build-node-${{ hashFiles('**/package.json', '**/_private/ionic/version.json') }}
            restore-keys: ${{ runner.os }}-build-node-

      - name: Convertigo generate application code
        env:
          C8O_SERVER: ${{ secrets.C8O_SERVEUR_TEST_CONVERTIGO }}
        run: |
          echo "Generate Mobile Builder App" && \
          sh gradlew --stacktrace --info generateMobileBuilder export -x compileMobileBuilder \
            -Pconvertigo.load.mobileApplicationEndpoint=$C8O_SERVER

      - name: Build and deploy on every push
        env:
          C8O_SERVER: ${{ secrets.C8O_SERVEUR_TEST_CONVERTIGO }}
          C8O_USER: ${{ secrets.C8O_USER_TEST_CONVERTIGO }}
          C8O_PASSWORD: ${{ secrets.C8O_PASSWORD_TEST_CONVERTIGO }}
        run: |
          echo "Deploying ref ${{ github.ref }} to server $C8O_SERVER"
          sh gradlew --stacktrace --info car deploy -x generateMobileBuilder \
            -Pconvertigo.deploy.server=$C8O_SERVER \
            -Pconvertigo.deploy.user=$C8O_USER \
            -Pconvertigo.deploy.password=$C8O_PASSWORD

      - name: Run post-deploy test plan
        env:
          TEST_SERVER_ENDPOINT: ${{ secrets.C8O_SERVEUR_TEST_CONVERTIGO }}
          C8O_PROJECT: Lib_Microsoft_Teams
        run: |
          python3 ./scripts/run_testcases.py

      - name: Save application project
        uses: actions/upload-artifact@v4
        with:
          name: project
          path: build/*.car

  release:
    if: github.ref_type == 'tag'
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download CAR File
        uses: actions/download-artifact@v4
        with:
          name: project

      - name: Deploy to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.car'
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
